name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  windows:
    name: Release Build For Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        buildMethod:
          - CodeBlaze.Editor.Build.Builder.BuildMonoRelease
          - CodeBlaze.Editor.Build.Builder.BuildIL2CPPRelease
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
            
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ matrix.buildMethod }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: |
            Build
            !**/*Ship*/**