# For ci we just need testing, as that would check compilation also
# Need to create a test suit and change this workflow

name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  linux:
    name: Build For Android
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildMethod:
          - CodeBlaze.Editor.Build.Builder.BuildAndroidRelease
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('.') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ matrix.buildMethod }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.buildMethod }}
          path: |
            Build
            !**/*DoNotShip*/**
            !**/*ButDontShipItWithYourGame*/**
  
  windows:
    name: Build For Windows
    timeout-minutes: 60
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        buildMethod:
          - CodeBlaze.Editor.Build.Builder.BuildWindowsRelease
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('.') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
            
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ matrix.buildMethod }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.buildMethod }}
          path: |
            Build
            !**/*DoNotShip*/**
            !**/*ButDontShipItWithYourGame*/**
