name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    name: Release Build For Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildMethod:
          - CodeBlaze.Editor.Build.Builder.BuildAndroidMonoRelease
          - CodeBlaze.Editor.Build.Builder.BuildAndroidIL2CPPRelease
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('.') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ matrix.buildMethod }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.buildMethod }}
          path: |
            Build
            !**/*DoNotShip*/**
            !**/*ButDontShipItWithYourGame*/**
  
  windows:
    name: Release Build For Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        buildMethod:
          - CodeBlaze.Editor.Build.Builder.BuildWindowsMonoRelease
          - CodeBlaze.Editor.Build.Builder.BuildWindowsIL2CPPRelease
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('.') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
            
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ matrix.buildMethod }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.buildMethod }}
          path: |
            Build
            !**/*DoNotShip*/**
            !**/*ButDontShipItWithYourGame*/**

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Zip artifacts
        run: |
          zip -r android-mono-${{ github.ref_name }}.zip artifacts/Build-CodeBlaze.Editor.Build.Builder.BuildAndroidMonoRelease/
          zip -r android-il2cpp-${{ github.ref_name }}.zip artifacts/Build-CodeBlaze.Editor.Build.Builder.BuildAndroidIL2CPPRelease/
          zip -r windows-mono-${{ github.ref_name }}.zip artifacts/Build-CodeBlaze.Editor.Build.Builder.BuildWindowsMonoRelease/
          zip -r windows-il2cpp-${{ github.ref_name }}.zip artifacts/Build-CodeBlaze.Editor.Build.Builder.BuildWindowsIL2CPPRelease/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            android-mono-${{ github.ref_name }}.zip
            android-il2cpp-${{ github.ref_name }}.zip
            windows-mono-${{ github.ref_name }}.zip
            windows-il2cpp-${{ github.ref_name }}.zip